---
name: Publish Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:lib:prod

      - name: Verify build output
        run: |
          ls -la dist/angular-google-tag-manager/
          cat dist/angular-google-tag-manager/package.json

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:lib:prod

      - name: Publish package
        run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: $GITHUB_TOKEN
        working-directory: dist/

      - name: Tag/Release on Push Action
        id: release_step
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: patch
          tag_prefix: v
          use_github_release_notes: true

